#=====================================================
#   BASIC INFORMATION
#=====================================================

name: "Dr. Ammar Ali Masad Alsinai"
title: "Assistant Professor of Mathematics & Engineering Sciences"
email: "your-email@onaizah.edu.sa"
address: "Unaizah, Al-Qassim, Saudi Arabia"
institution: "Onaizah Colleges â€“ College of Engineering & IT"

#=====================================================
#   PROFILE LINKS
#=====================================================

orcid: "https://orcid.org/0000-0002-5221-0574"
google_scholar: "https://scholar.google.com/citations?user=fXSyb0sAAAAJ"
scopus: "https://www.scopus.com/authid/detail.uri?authorId=57222957516"
wos: "https://www.webofscience.com/wos/author/rid/AAK-1025-2021"
researchgate: "https://www.researchgate.net"
linkedin: "https://www.linkedin.com/in/dr-ammar-alsinai-6930241b9/"

#=====================================================
#   SITE CONFIG
#=====================================================

url: "https://ammaralsinai1985-jpg.github.io"
baseurl: "/ammar-alsinai.github.io"

markdown: kramdown
highlighter: rouge
theme: minima
paginate: 10

#=====================================================
#   OPTIONAL SETTINGS (leave them as they are)
#=====================================================

permalink: pretty
timezone: Asia/Riyadh

collections:
  publications:
    output: true
  posts:
    output: true
  teaching:
    output: true
  portfolio:
    output: true
  talks:
    output: true
